name: IntegrationTest
on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
  push:
    branches:
      - main
    tags:
      - v*
    paths-ignore:
      - 'docs/**'
  schedule:
      - cron: '34 21 * * 4'

jobs:
  test:
    name: ${{ matrix.package.repo }}/${{ matrix.package.group }}
    strategy:
      fail-fast: false
      matrix:
        package:
          - {user: SciML, repo: SciMLBase.jl, group: Core}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core1}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core2}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core3}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core4}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core5}
          - {user: SciML, repo: SciMLSensitivity.jl, group: Core6}
    uses: "SciML/.github/.github/workflows/downstream.yml@v1"
    with:
      owner: "${{ matrix.package.user }}"
      repo: "${{ matrix.package.repo }}"
      group: "${{ matrix.package.group }}"
    secrets: "inherit"
